# Generated by Django 5.0.3 on 2024-04-19 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=128)),
                ('estado', models.CharField(choices=[('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado'), ('En proceso', 'En proceso'), ('Algunos reversos', 'Algunos reversos'), ('Devuelto', 'Devuelto')], max_length=20)),
                ('libro_contable', models.FileField(upload_to='')),
                ('formato', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(max_length=32)),
                ('numero_documento', models.CharField(max_length=32)),
                ('numero_cuenta', models.CharField(max_length=20)),
                ('banco', models.CharField(max_length=30)),
                ('tipo_transaccion', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=128)),
                ('telefono', models.CharField(max_length=30)),
                ('correo', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField()),
                ('fecha_modificación', models.DateTimeField()),
                ('desenglose', models.CharField(max_length=128)),
                ('aprobado_contador', models.BooleanField()),
                ('justificacion_contador', models.CharField(max_length=128)),
                ('aprobado_director', models.BooleanField()),
                ('justificacion_director', models.CharField(max_length=128)),
                ('tipo', models.CharField(max_length=32)),
                ('estado', models.CharField(choices=[('Pagado', 'Pagado'), ('Rechazado', 'Rechazado'), ('En proceso', 'En proceso'), ('Reversado', 'Reversado'), ('Saldo pendiente', 'Saldo pendiente'), ('Devuelto', 'Devuelto'), ('Pagado por socio', 'Pagado por socio')], max_length=20)),
                ('beneficiario', models.CharField(max_length=64)),
                ('monto', models.PositiveIntegerField()),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagos.lote')),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('descripcion', models.CharField(max_length=128)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pagos.lote')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('hash_contraseña', models.CharField(max_length=128)),
                ('correo', models.CharField(max_length=40)),
                ('ultimo_ingreso', models.DateTimeField()),
                ('es_administrador', models.BooleanField()),
                ('es_financiero', models.BooleanField()),
                ('es_director', models.BooleanField()),
                ('es_contador', models.BooleanField()),
                ('es_obra', models.BooleanField()),
                ('proyectos', models.ManyToManyField(to='pagos.proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('descripcion', models.CharField(max_length=128)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pagos.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='proyecto',
            name='usuarios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pagos.usuario'),
        ),
        migrations.AddField(
            model_name='lote',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pagos.usuario'),
        ),
    ]
